### ISSUE TITLE
.menu command

### ISSUE THREAD

**Issue by ghost** [Zeltoria/Clara-MD#1]
Keterangan limit / premium user malah undefined

**Comment by Zeltoria** [comment]
> Keterangan limit / premium user malah undefined

Ya Untuk Itu Emang Undifined Mas, Karna Logo/Characternya Ku Hapus Di Config.js

**Comment by ghost** [comment]
oala kirain ada apa, btw kok keterangan git clonenya bukan clone repo ini ya? malah disuruh clone repo lain

**Comment by Zeltoria** [comment]
> oala kirain ada apa, btw kok keterangan git clonenya bukan clone repo ini ya? malah disuruh clone repo lain

Ya Karna Aku Ganti Nick Dari Zeltoria Ke Xyroinee
