### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by PanzXx** [Zeltoria/Clara-MD#13]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'cfonts' imported from /data/data/com.termux/files/home/Clara-MD/index.js

**Comment by Zeltoria** [comment]
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'cfonts' imported from /data/data/com.termux/files/home/Clara-MD/index.js

module cfonts tidak terinstall ketik aja yarn add cfonts
