### ISSUE TITLE
button url / CTA ( Call to action)

### ISSUE THREAD

**Issue by EvelynXD** [Zeltoria/Clara-MD#21]
bang cara bikin button url/cta gimana bang sama product katalog buat di isi menunya dalem situ

kek gini kuranh lebihnya:
<img src="https://blog-assets.freshworks.com/live-chat-software/wp-content/uploads/2022/02/11163754/WhatsApp-button-kart.jpg" />

**Comment by Zeltoria** [comment]
> bang cara bikin button url/cta gimana bang sama product katalog buat di isi menunya dalem situ

Wa aja nih; 085150910870
