### ISSUE TITLE
Repo Name

### ISSUE THREAD

**Issue by xct007** [Zeltoria/Clara-MD#7]
Nama *repo* nya kok mirip 100% nama **mantan** gw, _kesel_ liat nya (/)

**Comment by Zeltoria** [comment]
> Nama _repo_ nya kok mirip 100% nama **mantan** gw, _kesel_ liat nya (/)

Njirr Nama Clara Ternyata Nama Mantan Sepuh Wkwkwkwkwkwk
Auto Jadi Gamon :v
